const path = {
  home: '/',
  login: '/sign-in',
  register: '/sign-up',
  authLogin: '/api/auth/login',
  authRegister: '/api/auth/register',
  logout: '/api/auth/log-out',
  settings: '/settings',
  staff: '/staff',
  staffRooms: '/staff/rooms',
  staffBooking: '/staff/bookings',
  staffShift: '/staff/shifts',
  staffProfile: '/staff/profile',
  manager: '/manager',
  managerRooms: '/manager/manage-room',
  managerStaff: '/manager/manage-staff',
  foods: '/foods',
  equipments: '/equipments',
  rooms: '/rooms',
  aboutUs: '/about-us',
  location: '/location',
  contact: '/contact',
  owner: '/owner',
  manageBuilding: '/owner/manage-building',
  manageAccount: '/owner/manage-account',
  schedule: '/staff/schedule',
};

export default path;
